name: Run Locust Tests on Commit
on:
  push:
    branches:
      - main
jobs:
  locust-test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v2
      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Step 4: Start Flask server
      - name: Start Flask server
        run: |
          python server.py & 
          echo "Waiting for Flask server to start"
          sleep 30